language: php

php:
  - 5.6
  - 7.0
  - hhvm

matrix:
    allow_failures:
        - php: 7.0
        - php: hhvm
        - php: 5.5.9
        - php: 5.5

env:
  global:
    - setup=basic
    - APP_ENV=testing
    - APP_DEBUG=true
    - APP_KEY=b4kJqxeKSQSLoQezsy0QBuUx50RHqEW9
    - DB_CONNECTION=sqlite
    - CACHE_DRIVER=file
    - SESSION_DRIVER=file
    - QUEUE_DRIVER=sync

install: travis_retry composer install --no-interaction --prefer-source

script:
    - mkdir -p build/logs
    - vendor/bin/phpunit

after_script:
    - travis_retry php vendor/bin/coveralls -v

notifications:
  slack: andela:FS1U7O0WWw91Uffll8EVrWLm
